name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/idiots-webserver-key.pem
        chmod 600 ~/.ssh/idiots-webserver-key.pem
    
    - name: Get Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}

    - name: Add SSH key and known hosts
      run: |
        ssh-keyscan -H ec2-13-125-169-9.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
    

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/idiots-webserver-key.pem ec2-user@ec2-13-125-169-9.ap-northeast-2.compute.amazonaws.com 'cd /Idiots/Idiots-backend && ./deploy.sh'
